substitutions:
  _IMAGE: australia-southeast1-docker.pkg.dev/natrio-platform/cloud-run-source-deploy/natrio-asia-pacific-natrio_2629_op-pod-automation/natrio-pod-automation
  _PROJECT: natrio-platform
  _REGION: australia-southeast1
  _SERVICE: pod-scanner

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args: [build, --tag, '${_IMAGE}:${SHORT_SHA}', .]

  - id: push
    name: gcr.io/cloud-builders/docker
    args: [push, '${_IMAGE}:${SHORT_SHA}']

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image=${_IMAGE}:${SHORT_SHA}'
      - '--project=${_PROJECT}'
      - '--region=${_REGION}'
      - '--labels=natrio-project=2629,commit-sha=${COMMIT_SHA}'
      - '--quiet'

images:
  - '${_IMAGE}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/natrio-shared-ops/serviceAccounts/pod-build-deployer@natrio-shared-ops.iam.gserviceaccount.com

timeout: 1200s
